### PR TITLE
only create table and index when not exists

### PR DESCRIPTION
**Pull request by mipopon**
Add checks if the indexes/tables exist to avoid exceptions.

enhancement from [Issue](https://github.com/BeerMoneyDev/nest-qldb/issues/9)

### CODE REVIEW

**Comment by KerryRitter** [comment]
I am very happy to see this! I hate the errors when it already exists. Can you please do a commit with the semantic release commit message format?

@benMain Thoughts?

**Comment by mipopon** [comment]
@KerryRitter @benMain Would be cool if it could be merged if there is no issue with it.

**Comment by benMain** [comment]
@mipopon merged

**Pull request merged**
